### PR TITLE
Various mixed gen5 working files

### PR DESCRIPTION
**Pull request by lepunk**
Hi, here are the generation 5 files as explained in issue #3 . The set is bit messy but hope it helps.
I've also included sketches for the whole generation

### CODE REVIEW

**Comment by gerwitz** [comment]
Could you include the Photoshop files? (We can't make SVGs without vectors.)

**Comment by lepunk** [comment]
@gerwitz they must be in the "PSD" folder

**Comment by gerwitz** [comment]
We've been trying to find a way to vectorize these, but they appear to have been "painted" not "drawn" in Photoshop, so there are only raster graphics.

They're good inspiration and would work great for anyone who needs just PNGs … if anyone wants to help make a "PNG only" package and update the website to share it (@dandesousa? ;-) ), that'd be awesome.

**Comment by gerwitz** [comment]
Big thanks to @pabluxo91 for vectorizing these

**Pull request closed without merging**
